name: wedding_invitation
description: Flutter Web Page for our wedding invitation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  admin_repository:
    path: packages/admin_repository
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  equatable: ^2.0.7
  firebase_auth: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  home_repository:
    path: packages/home_repository
  intl: ^0.19.0
  retry: ^3.1.2
  unlock_repository:
    path: packages/unlock_repository
  url_launcher: ^6.3.1
  url_launcher_web: ^2.3.3
  uuid: ^4.5.1
  video_player: ^2.9.2

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  melos: ^6.2.0
  mocktail: ^1.0.4
  plugin_platform_interface: any
  url_launcher_platform_interface: any
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/gif/
